<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PropertiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('properties')->insert([
            // [
            //     'nama' => 'Kost Harapan Jaya',
            //     'alamat' => 'Jl. Kebon Jeruk No. 12',
            //     'kota' => 'Jakarta Barat',
            //     'jeniskost_id' => 1, 
            //     'foto' => 'kost-harapan.jpg',
            //     'deskripsi' => 'Kost nyaman dan strategis dekat kampus dan pusat perbelanjaan.',
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'deleted_by' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nama' => 'Kost Bunga Melati',
            //     'alamat' => 'Jl. Cikutra No. 22',
            //     'kota' => 'Bandung',
            //     'jeniskost_id' => 2, // Kost Putri
            //     'foto' => 'kost-melati.jpg',
            //     'deskripsi' => 'Lingkungan tenang, cocok untuk mahasiswi dan pekerja.',
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'deleted_by' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nama' => 'Kost Harmoni',
            //     'alamat' => 'Jl. Diponegoro No. 8',
            //     'kota' => 'Yogyakarta',
            //     'jeniskost_id' => 3, 
            //     'foto' => 'kost-harmoni.jpg',
            //     'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'deleted_by' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            [
                'nama' => 'Kost Selly',
                'alamat' => 'Jl.Naskah 2, Sukarami, Kec. Sukarami, Kota Palembang, Sumatera Selatan 30961',
                'kota' => 'Palembang',
                'jeniskost_id' => 2,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kost Subari',
                'alamat' => 'Jl. Sultan M. Mansyur, Lrg. Lb. Keranji, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30136',
                'kota' => 'Palembang',
                'jeniskost_id' => 3,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Zainal Makmur Kost',
                'alamat' => 'Jl. Madang, Lrg. Makmur V, Sekip Jaya, Kec. Kemuning, Kota Palembang, Sumatera Selatan 30114',
                'kota' => 'Palembang',
                'jeniskost_id' => 2,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Zainal Makmur Kost 2',
                'alamat' => 'Jl. Madang, Lrg. Makmur V, Sekip Jaya, Kec. Kemuning, Kota Palembang, Sumatera Selatan 30114',
                'kota' => 'Palembang',
                'jeniskost_id' => 2,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kost 1076',
                'alamat' => 'Jl. Demang Lebar Daun No.2998, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30961',
                'kota' => 'Palembang',
                'jeniskost_id' => 3,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kost Putri 12 Tanjung',
                'alamat' => 'Jl. Sultan M. Mansyur, Lrg. Hasan As No.12, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30139',
                'kota' => 'Palembang',
                'jeniskost_id' => 2,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kost Afif',
                'alamat' => 'Jl. Sultan M. Mansyur, Lorong Kolam, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30118',
                'kota' => 'Palembang',
                'jeniskost_id' => 3,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kost Hijau Barokah',
                'alamat' => 'Jl. Sultan M. Mansyur Lorong Kolam No.2401, RT.33/RW.11, Bukit Lama, Kota Palembang, Sumatera Selatan 30139',
                'kota' => 'Palembang',
                'jeniskost_id' => 3,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mawar Kost',
                'alamat' => 'Jl. Sultan M. Mansyur Lorong Kolam No.2424, RT.33/RW.11, Bukit Lama, Kota Palembang, Sumatera Selatan 30139',
                'kota' => 'Palembang',
                'jeniskost_id' => 3,
                'foto' => 'kost-harmoni.jpg',
                'deskripsi' => 'Kost campur dengan fasilitas lengkap dan akses mudah ke mana saja.',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
